export const envSchema = {
  type: "object",
  required: [
    "PORT",
    "HOST",
    "DATABASE_URL",
    "JWT_ACCESS_SECRET",
    "JWT_REFRESH_SECRET",
    "REDIS_URL",
    "AI_ENCRYPTION_KEY",
  ],
  properties: {
    PORT: { type: "string", default: "3000" },
    HOST: { type: "string", default: "0.0.0.0" },
    NODE_ENV: { type: "string", default: "development" },
    DATABASE_URL: { type: "string" },
    JWT_ACCESS_SECRET: { type: "string" },
    JWT_REFRESH_SECRET: { type: "string" },
    JWT_ACCESS_EXPIRES: { type: "string", default: "15m" },
    JWT_REFRESH_EXPIRES: { type: "string", default: "7d" },
    REDIS_URL: { type: "string" },
    CORS_ORIGIN: { type: "string", default: "http://localhost:3001" },
    SMTP_HOST: { type: "string" },
    SMTP_PORT: { type: "string", default: "2525" },
    SMTP_USER: { type: "string" },
    SMTP_PASS: { type: "string" },
    SMTP_FROM: { type: "string" },
    ALERT_ERROR_THRESHOLD: { type: "string", default: "10" },
    RETENTION_DAYS: { type: "string", default: "30" },
    INSIGHTS_CRON: { type: "string", default: "0 */6 * * *" },
    AI_ENCRYPTION_KEY: { type: "string" },
  },
};
